""" 🎵 Задача: «Кратчайшая мелодия»

Дана строка `heet_music`, состоящая из символов, обозначающих ноты:
`A`, `B`, `C`, `D`, `E`, `F`, `G`.

Нужно **найти самую короткую подстроку**, которая содержит **все семь различных нот** хотя бы по одному разу.

Если таких подстрок несколько одинаковой длины, нужно выбрать **ту, которая встречается раньше всех** в исходной строке.

---

### 🔍 Пример

Для строки:

```
ADCEEFAGABDC
```

все 7 нот (`A, B, C, D, E, F, G`) впервые встречаются вместе в подстроке

```
EFAGABDC
```

Это и есть ответ, так как это кратчайшая последовательность, содержащая все ноты, и она появляется первой.
"""

sheet_music = "GDGECCBCGDFADFBAABDCBCFABCCDCCAGDACFAEFFFEAEEDAFEFAEFDAFDEGCABBFDDFCCAFFFABDDCCDCCAGCBCDFABGBGFFAFGGACFADBAFCEBFBAEDFEFGDEBFBGAGGBGACDDBDDAAECDBFDEEDDCBCCGDFAGDCEDBECEEAFGEBGAAFCCCCBDGADDGDCGGDBDGBFCBEFGEDAEFBAGFGGGEAFFDAEABFFFGFAEFCGEDDADBAEAFBDAFECGGGDECDDGDGFCGGFBGCACCFEFFFAAAFACECFEEECAEDEEFBEBDFFDAADEDABBACBFBBDAFGEDCDFFGCGCEDABGDGBFDACECCGGFCCFDFFBFCGEBFBGBDCGFCFDFGECDDEEACDGACAGEDEDDBDFFABDACGFCEDABDGBCEFGBEBCBCBECAAGCGFCCFAEFAEFGBCBGCCBGAABADECCBFGCEDEGGCCGAEEBGECBDCADCFDDAFBAGEFBGGFECAAABABDDEACFGBFCAACCBCCEBEAGDBDGBGGGAAADADBFCAACFEBCGABDAFDCGDFECABBDGFCCDADCGDEDDCEBCFDBBDACEAAACCFAFEBAABDFDAAEDECDCBGDDACEDAECDDEACBCABBBDEFEDGDBAAECECBECGFGEBABGCDCGEDEAGFDEBFBDFFAGEBAABAGCBFEFBEBCCAGGACBBFGFGFFDDGAAAAADCBECFBDACFBEDACADAFFGEFECFFDCDFGFAAFCCCDBDBDCFDFDDBDFGDCGFAAGBAEEFBFFEEBAFBBEFEGFEBGGBFGFBBAAFCCFEADAFECGCEGECAEBCDDCCGGADACEBDCGDGBCGFFEFGGGBDADDFDCFCAAAEBEAGGDFDGAFGBGGDBGBBDEBFABFBCCFBADGDAAAFGFECBDCGCEDECEAEBEFGDGEEBADCBCADEBCDGEGCGCEDGAFFDBGGAEDABDDEFFFBGEBBGCDGFACADAFGAGE"

notes = set('ABCDEFG')
for i in range(len(sheet_music)-7):
    if set(sheet_music[i:i+7]) == notes:
        print(sheet_music[i:i+7])
        break

# FDEGCAB
# FDEGCAB



